{
  "name": "__NAME__",
  "version": "1.0.0",
  "private": true,
  "description": "An animated desktop pet generated by the desktop-pet skill.",
  "main": "main.js",
  "scripts": {
    "start": "electron . --ozone-platform-hint=auto"
  },
  "devDependencies": {
    "electron": "^31.0.0"
  }
}
